spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/zarzadzanie_osiedlem
    username: postgres
    password: admin
    initialization-mode: always
    data: classpath:/data.sql
server:
  port: 8080